services:
  server:
    depends_on:
      db:
        condition: service_healthy

    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 8000:8000
    volumes:
      - .:/pipou-blog
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgres://pipou:password@db:5432/pipoubdd
    # Utiliser les variables d'environnement si disponibles, sinon les valeurs par défaut
    user: "${UID:-1000}:${GID:-1000}"
    command: python3 pipou_blog/manage.py runserver 0.0.0.0:8000

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pipoubdd
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=pipou
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pipou -d pipoubdd"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: